# FROM adicionando a ultima versao do python 3 na imagem

FROM python:3.13.0

# WORKDIR muda para o diretorio /app

WORKDIR /app

# Copia o arquivo script_python_etapa03.py para a pasta /app

COPY script_python_etapa03.py /app/

# Comandos que serao executados no container
  
CMD ["python", "/app/script_python_etapa03.py"]