# FROM adicionando a ultima versao do python 3 na imagem

FROM python:3.13.0

# WORKDIR muda para o diretorio /app

WORKDIR /app

# Copia o arquivo carguru.py para a pasta /app

COPY carguru.py /app/

# Comandos que serao executados no container

CMD ["python", "carguru.py"]